'use client';

import {
  LayoutDashboard,
  Activity,
  Users,
  UserPlus,
  Calendar,
  BedDouble,
  Stethoscope,
  Pill,
  FlaskConical,
  CreditCard,
  BarChart3,
  Settings,
  Search,
  Bell,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Sun,
  Moon,
  Heart,
  TrendingUp,
  TrendingDown,
  List,
  Plus,
  FileText,
  Package,
  PanelLeft,
  AlignJustify,
  LogOut,
  User,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  Loader2,
  Home,
  FolderOpen,
  ClipboardList,
  Syringe,
  Microscope,
  Receipt,
  FileBarChart,
  Cog,
  Shield,
  UserCog,
  Building,
  type LucideIcon,
} from 'lucide-react';

// Icon mapping for dynamic usage
export const Icons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  home: Home,
  emergency: Activity,
  users: Users,
  userPlus: UserPlus,
  user: User,
  userCog: UserCog,
  calendar: Calendar,
  bed: BedDouble,
  stethoscope: Stethoscope,
  pill: Pill,
  flask: FlaskConical,
  microscope: Microscope,
  syringe: Syringe,
  creditCard: CreditCard,
  receipt: Receipt,
  chart: BarChart3,
  fileBarChart: FileBarChart,
  settings: Settings,
  cog: Cog,
  search: Search,
  bell: Bell,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  sun: Sun,
  moon: Moon,
  heart: Heart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  list: List,
  clipboardList: ClipboardList,
  plus: Plus,
  file: FileText,
  folder: FolderOpen,
  box: Package,
  sidebar: PanelLeft,
  horizontal: AlignJustify,
  logout: LogOut,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  alertCircle: AlertCircle,
  loader: Loader2,
  shield: Shield,
  building: Building,
};

// Get icon by name (case-insensitive)
export const getIcon = (name: string): LucideIcon => {
  // Try exact match first
  if (Icons[name]) return Icons[name];

  // Try lowercase
  const lowerName = name.toLowerCase();
  const found = Object.keys(Icons).find((key) => key.toLowerCase() === lowerName);

  return found ? Icons[found] : FileText;
};

// Re-export commonly used icons
export {
  LayoutDashboard,
  Activity,
  Users,
  UserPlus,
  Calendar,
  BedDouble,
  Stethoscope,
  Pill,
  FlaskConical,
  CreditCard,
  BarChart3,
  Settings,
  Search,
  Bell,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Sun,
  Moon,
  Heart,
  TrendingUp,
  TrendingDown,
  List,
  Plus,
  FileText,
  Package,
  PanelLeft,
  AlignJustify,
  LogOut,
  User,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  Loader2,
};

export type IconName = keyof typeof Icons;